"! AMDP Table Function Template
"! Usage: Consumed by CDS table function entity
"! Replace: {{CLASSNAME}}, {{FUNCTION}}, {{ENTITY}}, {{FIELDS}}, {{TABLE}}
CLASS {{CLASSNAME}} DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.

    CLASS-METHODS {{FUNCTION}}
      FOR TABLE FUNCTION {{ENTITY}}.
ENDCLASS.

CLASS {{CLASSNAME}} IMPLEMENTATION.
  METHOD {{FUNCTION}} BY DATABASE FUNCTION
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING {{TABLE}}.

    RETURN SELECT
      {{FIELDS}}
    FROM {{TABLE}}
    WHERE {{FILTER_CONDITION}};
  ENDMETHOD.
ENDCLASS.
